# Generated by Django 2.0.5 on 2018-07-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuangwuyiStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('style_descripe', models.TextField()),
                ('style_example', models.ImageField(upload_to='')),
            ],
        ),
    ]
