# Generated by Django 2.0.5 on 2018-07-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=200)),
                ('method_descripe', models.CharField(max_length=2000)),
                ('method_lsno', models.IntegerField()),
                ('chapter_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAndroidUtil.ChapterItem')),
            ],
        ),
    ]
