# Generated by Django 2.0.5 on 2018-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0004_chapter_chapter_descripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmethod',
            name='method_type',
            field=models.CharField(default='构造方法', max_length=50),
            preserve_default=False,
        ),
    ]
