# Generated by Django 2.0.5 on 2018-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0005_itemmethod_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='methonparameter',
            name='parameter_descripe',
            field=models.CharField(default='参数描述', max_length=1000),
            preserve_default=False,
        ),
    ]
