# Generated by Django 2.0.5 on 2018-07-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0006_methonparameter_parameter_descripe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MethonParameter',
            new_name='MethodParameter',
        ),
    ]
