# Generated by Django 2.0.5 on 2018-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0007_auto_20180716_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_descripe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chapteritem',
            name='item_descripe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemmethod',
            name='method_descripe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='methodparameter',
            name='parameter_descripe',
            field=models.TextField(),
        ),
    ]
