# Generated by Django 2.0.5 on 2018-07-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0008_auto_20180716_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_lsno', models.IntegerField()),
                ('result_type', models.CharField(max_length=200)),
                ('result_descripe', models.TextField()),
                ('item_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloAndroidUtil.ItemMethod')),
            ],
        ),
    ]
