# Generated by Django 2.0.5 on 2018-07-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloAndroidUtil', '0010_sometangshi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sometangshi',
            old_name='remark',
            new_name='remark_tang',
        ),
    ]
